"""create orders table

Revision ID: 77fa4095ce7e
Revises: 353519207212
Create Date: 2026-05-18 17:31:29.654584

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "77fa4095ce7e"
down_revision: str | Sequence[str] | None = "353519207212"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
